### ISSUE TITLE
i18n in javascript scripts

### ISSUE THREAD

**Issue by honestserpent** [koalazak/i18n-express#22]
Hello, my i18n is working fine on static content. When I render a page I do have the content changing according to the language.

But, i have some javascript scripts that need to apply some text transformation on certain events. For instance, I have a title that changes everytime you click a button.

The initial title is localized, but when the script acts, I don't have access to the i18n variable.

How do I do this?

**Comment by ajperez81** [comment]
I am facing the same issue.

Currently I have solved it by having two different i18n libraries: i18n-express for the EJS templates, and i18njs for the static JS resources. It's annoying, but it works.

Other than that, I guess you could generate your JS files dynamically in the same way that you do for the HTML ones. I chose not to do it this way because I guess it would impact performance.

Hopefully there is a better way to do it?

**Comment by koalazak** [comment]
Yes, this is a lib to render i18n texts in the backend. If you put texts in your frontend you will need other library to work on the front side.
Other option, as @ajperez81 mention, you can render the js files like an html file and generate a js file with the translated texts (maybe a single lang.js file with all texts)
